# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  download:test-dataset:
    cmds:
      - cmd: ./tests/download_test_bag.sh
